### ISSUE TITLE
Custom allocators for ArduinoJSON

### ISSUE THREAD

**Issue by maxdee** [a3lab/morphoses#115]
We were concerned about no longer having a fixed size StaticJsonDocument for ArduinoJson. Found this which has some esp32 specific info. Might be good to add, might not be needed.
https://arduinojson.org/v7/api/jsondocument/#allocator
see also : https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/mem_alloc.html

**Comment by sofian** [comment]
We ran some tests and it doesn't look like there are memory leaks so I guess we can set this issue aside for now.
