### ISSUE TITLE
Le robot "shut down" en lisant la batterie qui retourne zéro - possiblement dû à problème de thread

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#116]

**Comment by sofian** [comment]
@etiennemontenegro J'ai l'impression que ce problème a été résolu, non?

**Comment by etiennemontenegro** [comment]
Ce problème, n'est pas arriver depuis qu'on a travaillé au labo en avril. Je pense que les sémaphores, ont fait la travaille. Ce issue pourrait être fermé.
