### ISSUE TITLE
Le mode "deep sleep" après un "battery critical" semble rebooter le robot plutôt que le mettre en deep sleep

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#141]
Lié à #140 

Le robot1 est entré en mode "deep sleep" suite à un "battery critical". Il a ensuite rebooté dû à ESP_RST_WDT.

Possiblement un problème similaire à ceci: https://github.com/espressif/arduino-esp32/discussions/8206

**Comment by etiennemontenegro** [comment]
Référence : https://lastminuteengineers.com/esp32-sleep-modes-power-consumption/

"When the chip wakes up from deep sleep, it performs a reset and begins program execution from the beginning."

Ça explique pourquoi les robots redémarrent lorsqu'ils tombent en deep sleep. Peut-être qu'on peut seulement les mettres en light sleep si on ne souhaite pas qu'ils redémarrent

**Comment by sofian** [comment]
@etiennemontenegro J'ai l'impression que ce bug est corrigé. Un des robots est entré en mode "deep sleep" hier pendant la documentation et ça s'est produit.

**Comment by sofian** [comment]
Je ferme ce bug.
