### ISSUE TITLE
"Fail nicely" / gérer la situation où le système de UWB envoie des NaN

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#154]

**Comment by etiennemontenegro** [comment]
On gère déjà la situation dans le code en sortant de la fonction si l'on reçoit "NaN".
https://github.com/mXlab/morphoses/blob/6e9fb379945e35dceed6d241e32d1acae4795764/Arduino/morphose_platformio/src/communications/asyncMqtt.cpp#L328-L331 #
