### ISSUE TITLE
Les batteries auraient avantage à avoir un peu plus de capacité

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#16]
On a fait des tests dans le temps pour constater la baisse de voltage de:
 1. la batterie pour le IMU (Li-ion 850 mAh 3.7V) : voltage initial 4.15V; voltage drop d'environ 0.17V par heure
 2. la batterie des moteurs (SLA 1200 mAh 12V): voltage initial 13.3V; voltage drop d'environ 0.52V par heure

Sur une projection d'un temps de "roulement" de 8 heures on arriverait à:
 1. 2.79 V restants pour la batterie IMU (assez "limite" car le ESP32 roule à minimum 2.7V)
 2. 9.14 V restants pour la batterie des moteurs (pas mal en-dessous du voltage requis pour les moteurs -- 12V)

Il faudrait donc augmenter la capacité des batteries (suggestion: au moins 150% ou doubler).

**Comment by gapzap** [comment]
Proto#3: 12v pour moteur NIMH 3000mAh (2.5x capacité), LIPO des ESP: 2000mAh (était 850 ou 1200mAh)
