### ISSUE TITLE
Permettre la recharge du board IMU depuis l'extérieur

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#17]

**Comment by gapzap** [comment]
Proto#3: recharge et programmation(USB) maintenant dispo sans ouvrir la boule. Aussi commutateur ON/OFF

**Comment by gapzap** [comment]
![IMG_7058](https://user-images.githubusercontent.com/46546355/85876964-7691af00-b7a4-11ea-98d7-23e02835bcf8.JPG)

**Comment by sofian** [comment]
J'ai l'impression que ceci est réglé, je ferme le ticket. @gapzap
