### ISSUE TITLE
Il arrive souvent que le balancier fasse un "flip" dans le proto 3b

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#52]
Ceci arrive en particulier avec la "skin" 2 qui est plus bulbeuse et plus lourde. Il faudrait probablement simplement ajouter du poids sur le balancier.

**Comment by gapzap** [comment]
essaie de ralentir la vitesse d'avancement (-10 a 15% disons) question que le momentum du contrepoids est le temps de faire effet.

**Comment by sofian** [comment]
@gapzap Je pense que nous opérons déjà à une vitesse réduite mais je pourrai faire des tests supplémentaires.

**Comment by sofian** [comment]
@gapzap Nous avions pris les notes suivantes: "3B tendance à fliper = surement du au fait que le poid était débalancé à cause du skin 2 + pas mis le « bouchon » sur l’autre pôle. Au besoin on pourait quand même en ajouter plus sur les côtés de la batterie"

**Comment by sofian** [comment]
Peut-être relié au fait qu'il n'y avait pas de bouchon au moment où on a observé ceci. A monitorer.

**Comment by sofian** [comment]
Je ferme ce bug pour le moment, voir si cela se reproduit avec le nouveau design.
