### ISSUE TITLE
Les couvercles ont tendance à se "dévisser"

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#8]
Il faut trouver une solution à ça. On avait essayé de les barrer avec des vis en métal mais le plastique avait alors tendance à craquer.

**Comment by gapzap** [comment]
plaques métal + vis

**Comment by gapzap** [comment]
![IMG_7070](https://user-images.githubusercontent.com/46546355/85876840-48ac6a80-b7a4-11ea-8435-d164412ac906.JPG)

**Comment by sofian** [comment]
Réglé.
