### ISSUE TITLE
Faire des tests sur le réseau sans fil et vérifier les logs en cas de déconnection

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#83]

**Comment by gapzap** [comment]
Sofian, fais-moi un capture avec wireshark, si possible avec le bug ;-) je pourrai analysé le data.

**Comment by sofian** [comment]
On va s'aider d'un système de logging sur les ESP (#95) et ensuite "stress-tester" les ESP avec l'ancien *et* le nouveau code pour essayer de déceler les problèmes. Dans le but d'essayer de corriger le bug du streaming interrompu (#91).

**Comment by sofian** [comment]
On a fait quelques progrès aujourd'hui.

Il semble y avoir des interférences avec le MQTT quand celui-ci se "déconnecte" car il essaie alors de se reconnecter / pendant ce temps le ESP32 n'écoute plus les messages.

Les problèmes ont commencé à partir du moment où on a allumé les LEDs à fond (255, 255, 255, 255). Éventuellement on a commencé à avoir des problèmes. Ça ne semble pas venir du code Python a priori.

Autre hypothèse: boucle while infinie liée aux IMU.

**Comment by sofian** [comment]
Je pense que ces problèmes sont maintenant réglés.
