### ISSUE TITLE
Créer un système de logging pour monitorer les problèmes possibles sur le ESP32

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#95]
Utiliser le file system de la flash du ESP pour logger dans un ou plusieurs fichiers.

Voici les choses importantes à logger:
- Le statut de connection et déconnection du wifi (+ des infos complémentaires comme codes d'erreur, force du signal, etc.)
- Le statut de connection au MQTT
- Les infos de connection au OSC et les changements (eg. changement de IP destinataire)
- Le statut des batteries et statuts reliés (low, critical)
- Le statut des IMU (connecté, déconnecté, erreur, etc.)
- Des informations sur les moteurs (notamment en cas de surchauffe)

Il faut aussi pouvoir accéder facilement au système de fichier et aller lire le log.

**Comment by sofian** [comment]
@etiennemontenegro Est-ce que c'est terminé? Que reste-t-il à faire (à part des tests)?

**Comment by etiennemontenegro** [comment]
C'est à tester. Peut-être ajouter plus de message de logging. Je n'en ai pas mis pour la connexion au mqtt et pas mis pour la température des moteurs

**Comment by sofian** [comment]
Je vais fermer ceci car je pense que le système est en place, même s'il reste des choses à arranger.
