### ISSUE TITLE
Refactorer le code du ESP pour tenter de "sanitiser" le code

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#96]

**Comment by sofian** [comment]
@etiennemontenegro Je vais m'occuper du refactoring pour toute la partie des LEDs / animations (j'ai commencé).

**Comment by sofian** [comment]
@etiennemontenegro Si ceci est terminé, fermer.

**Comment by etiennemontenegro** [comment]
Il n'y a que le code de l'ota qui n'a pas encore été modifier

**Comment by sofian** [comment]
Je vais fermer ce bug et ouvrir un bug pour l'OTA.
